# Generated by Django 4.0.5 on 2022-06-04 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_models'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Models',
            new_name='Product',
        ),
    ]
